album_main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls', namespace='music')),
]

music/urls.py
from django.conf.urls import url

from .import views
app_name = 'music'

urlpatterns = [

    # /music/
    url(r'^$', views.index, name='index'),

    # /music/<album_id>/>
    url(r"^(?P<album_id>[0-9]+)/$", views.detail, name='detail'),

    # /music/<album_id>/favorite/
    url(r"^(?P<album_id>[0-9]+)/favorite/$", views.favorite, name='favorite')
]

music/models.py
from django.db import models


# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' : ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title


# ForeignKey means each Song link with Album
'''on_delete = model.CASCADE means that like RED pk1 is Album we want to delete and a Song is a part of Album 
then if delete Album Red the any Song link to this its automatically delete'''

# we make some change music model in django database
# run $ python manage.py makemigarations music

music/views.py
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from rest_framework.response import Response
from .models import Album, Song


def index(request):
    print('index')
    all_albums = Album.objects.all()

    return render(request, 'music/index.html', {"all_albums": all_albums})


def detail(request, album_id):
    # try:
    #     album = Album.objects.get(pk=album_id)
    #
    # except Album.DoesNotExist:
    #     raise Http404('Album does not exit')
    album = get_object_or_404(Album, pk=album_id)

    return render(request, 'music/details.html', {"album": album})

    # return JsonResponse({"name": album.album_title, "artist": album.artist})


def favorite(request, album_id):

    album = get_object_or_404(Album, pk=album_id)
    # print(album_id ,': ',album, ':',album.song_set.get(pk=request.POST['song']))
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
        print(selected_song)
    except (KeyError, Song.DoesNotExist):
        print("exception")
        return render(request, 'music/details.html', {
            'album': album,
            'error_message': 'You did not selected a valid song',
        })
    else:

        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/details.html', {'album': album})

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link ref="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
</head>
<body>
    <nav class="navbar navbar-inverse">

        <div class=" container-fluid ">

                <!-- header -->
                <div class=" navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'music:index' %}"> Home </a>
                </div>
                <!--  Item  -->
    <!--            <div class="collapse navabar-collapse">-->
                <div class="navbar-collapse">
                    <ul class="=nav navbar-nav navbar-left">
                        <li class="">
                            <a href="{% url 'music:index' %}">
                                <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                            </a>
                        </li>
                        <li class="">
                            <a href="#">
                                <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                            </a>
                        </li>
                    </ul>
                </div>
                    <form class="navbar-form navbar-left" role="search" method="get" action="#">
                        <div class="form-group">
                            <input type="text" class="form-control" name="q" value="">
                        </div>
                        <button type="submit" class="btn btn-default" >Search</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="{% url 'music:index' %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Albums
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'music:index' %}">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                            </a>
                        </li>
                    </ul>
                </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

music/templates/music/details.html
{% extends 'music/base.html' %}
<!--{% block title %}Album Detail{% endblock %}-->
<title>asdfghj</title>
{% block body %}
    <img src="{{ album.album_logo }}" width="400" height="400" />

    <h1> {{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>

    <!--<ul>-->
    <!--    {% for song in album.song_set.all %}-->
    <!--        <li>{{song.song_title}} &#45;&#45; {{song.file_type}}</li>-->
    <!--    {% endfor %}-->
    <!--</ul>-->

    {% if error_message %}
    <p> <strong>{{error_message}}</strong></p>
    {% endif %}

    <form action="{% url 'music:favorite' album.id %}" method="POST">
        {% csrf_token %}
        {% for song in album.song_set.all %}
            <input type="radio" id="song{{forlorn.counter}}" name="song" value = {{song.id}} />
        <label for="song{{forlorn.counter}}">
            {{ song.song_title}}
            {{song.id}}
            {% if song.is_favorite%}
                <img src="https://cdn3.iconfinder.com/data/icons/basicolor-votting-awards/24/198_star_favorite_vote_achievement-512.png" width="15" height="15"/>
            {% endif%}
        </label><br>
        {% endfor %}
        <input type="submit" value="Favorite" />
    </form>
{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
    {% if all_albums %}
    <h3>Here All My Albums</h3>
    <ul>
     {% for albums in all_albums %}
        <li>
<!--                <a href="/music/{{ albums.id }}/">{{albums.artist}} : {{ albums.album_title }}</a><br>-->
            <a href="{% url 'music:detail' albums.id %}">{{albums.artist}} : {{ albums.album_title }}</a><br>

        </li>
    {% endfor %}
    </ul>
    {% else %}
        <h1>No album are present</h1>

    {% endif %}
{% endblock %}